# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Marc-Antoine Sauvé
tagline:          'Mobile developer'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://masauve.com
baseurl:          /

author:
  name:           'Marc-Antoine Sauvé'
  url:            https://twitter.com/masauve_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/madeinqc/madeinqc.github.io
