# Dependencies
highlighter:      rouge
gems:             [jekyll-paginate, jekyll-gist, pygments.rb]

# Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Marc-&#8203;Antoine Sauvé
tagline:          'Mobile developer'
description:      ''
url:              http://masauve.com
baseurl:          /

author:
  name:           'Marc-Antoine Sauvé'
  url:            https://twitter.com/masauve_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/madeinqc/

bitbucket:
  repo:           https://bitbucket.org/madeinqc/
